apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-1
  labels:
    app: mysql
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - image: mysql:8
      imagePullPolicy: Always
      name: mysql
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_DATABASE
          value: wordpress
      envFrom:
        - secretRef:
            name: mysql-secret
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
  volumes:
    - name: mysql-volume
      hostPath:
        path: /k8sdata/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP
