apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: nginx
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/log/nginx
        name: log-volume
      - mountPath: /etc/nginx
        name: nginx-conf
  - image: fluentd:latest
    imagePullPolicy: IfNotPresent
    name: fluentd
    volumeMounts:
      - mountPath: /logs
        name: log-volume
      - mountPath: /fluentd/etc
        name: fluent-conf
  volumes:
    - name: log-volume
      emptyDir: {}
    - name: nginx-conf
      configMap:
        name: nginx-conf
    - name: fluent-conf
      configMap:
        name: fluent-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort